services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: spring-mongo
      MONGO_INITDB_ROOT_USERNAME: spring-mongo
      MONGO_INITDB_ROOT_PASSWORD: spring-mongo
    ports:
      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

#volumes:
#  mongo_data: